#! /bin/bash

NAME="abcss_ws"
APP="$1"

if [ "$APP" == "Frontend" ]; then
    ENV="$2"
    if [ "$ENV" != "Develop" ] && [ "$ENV" != "Production" ]; then                       # check if parameter given
        echo "Please provide secondary argument Develop or Production!"              # echo error message
    else
        echo "Starting $NAME $APP!"
        export APP
        export ENV
        cd /web_app/ws   .                                                                 # get to project
        service nginx start                                                              # start nginx
        gunicorn manage:app --config etc/green_unicorn/green_unicorn_settings.py         # start gunicorn with config file
    fi
elif [ "$APP" == "API" ]; then
    ENV="$2"
    if [ "$ENV" != "Develop" ] && [ "$ENV" != "Production" ]; then                       # check if parameter given
        echo "Please provide secondary argument Develop or Production!"              # echo error message
    else
        echo "Starting $NAME $APP!"
        export APP
        export ENV                                                                   # set env type from arg
        cd /web_app/ws   .                                                             # get to project
        service nginx start                                                          # start nginx
        gunicorn manage:app --config etc/green_unicorn/green_unicorn_settings.py     # start gunicorn with config file
    fi
else
    echo "Please provide primary argument API or Frontend!"                          # echo error message
fi
